### ISSUE TITLE
Support excel files in tabular module

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#201]
Notes:
- each sheet will be represented as a separate "table entity", see https://github.com/kbss-cvut/s-pipes/pull/203#discussion_r1313848709

A/C:
- within output RDF it is possible to query which columns or rows where merged
- there is optional parameter to process only one sheet
- functionality is tested with JUNIT tests including test with multiple sheets
- module should support parsing multiple CSV files as well
- if implemented using property holding mime-type value, it should be checked that combination of delimiter value and mime-type values are together consistent
- TabularModule main documentation is revised by @blcham (especially default behaviour, process-specific-sheet-in-xls-file should be refactored to address multiple tables, is it ok to replace cell value '\t' to '  ' in HTML and excel? )

Should be implemented after #204

**Comment by rodionnv** [comment]
@blcham Tests are not working for TabularModule, I have 8 failed tests, 1 passed and 3 ignored.
In all failed tests the problem is that casting `cz.cvut.spipes.modules.model.Column` or `cz.cvut.spipes.modules.model.TableGroup` to `cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable` throws `java.lang.ClassCastException`
Example `executeWithSimpleTransformation()`. I am not sure where the problem is.

![image](https://github.com/kbss-cvut/s-pipes/assets/130922166/9628c6e3-5431-45b3-b956-858add65c43b)

**Comment by blcham** [comment]
@rodionnv I have added requirment to "module should support parsing multiple CSV files as well" (it is basically same as support for multiple excel sheets)
